Vagrant.configure("2") do |config|
config.vm.box = "jacqinthebox/windowsserver2016"
config.vbguest.auto_update = false
config.vm.hostname = "windows1"
# Exposer les ports WinRM
#config.vm.network "forwarded_port", guest: 5985, host: 5985, id: "winrm"
#config.vm.network "forwarded_port", guest: 5986, host: 5986, id: "winrm-ssl"
config.vm.provider "virtualbox" do |vb|
  vb.memory = "4096"
  vb.cpus = 2
end
  config.vm.network "private_network", ip: "192.168.56.14" 
  config.vm.communicator = "winrm" 
  config.winrm.username = "Administrator"
  config.winrm.password = "vagrant"
  config.vm.provision "shell", path: "setup.ps1"
end